#####################################
# mysite/urls.py autogenerated
#####################################

from django.conf.urls import patterns, include, url

# generic views system
from django.views.generic import DetailView, ListView
from polls.models import Poll

# to enable the admin and activate the admin site:
# to map URL root to application
#from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Example 1:
    #url(r'^polls/$', 'polls.views.index'),
    #url(r'^polls/(?P<poll_id>\d+)/$', 'polls.views.detail'),
    #url(r'^polls/(?P<poll_id>\d+)/results/$', 'polls.views.results'),
    #url(r'^polls/(?P<poll_id>\d+)/vote/$', 'polls.views.vote'),

    # Example 2:
    #url(r'^polls/', include(polls.urls)),

    # to enable the admin and activate the admin site:
    # to map URL root to application
    #url(r'^admin/', include(admin.site.urls)),

    # use of generic views
    # ListView generic view: <app name>/<model name>_list.html
    # DetailView generic view: <app name>/<model name>_detail.html
    url(r'^$',
        ListView.as_view(
            queryset=Poll.objects.order_by('-pub_date')[:5],
            context_object_name='latest_poll_list',
            template_name='polls/index.html')),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/detail.html')),
    url(r'^(?P<pk>\d+)/results/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/results.html'),
        name='poll_results'),
    url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote'),

)
